<form action="agregarcategoria" method="POST">
  <div class="mb-3">
    <label for="categoria" class="form-label">Ingresar Nueva Categoria</label>
    <input type="text" class="form-control" id="categoria" aria-describedby="emailHelp" name="categoria">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Gama</label>
    <select name="gama" id="" class="form-select form-select-sm" aria-label="Small select example">
      <option value="gamaalta"> Alta</option>
      <option value="gamamedia"> Media</option>
      <option value="gamabaja"> Baja</option>
    </select>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>