<?php include_once 'header.phtml';?>
<h3 >CONTROL DE INVENTARIO</h3>
<?php require 'templates/formAltaProductos.phtml';?>
<div class="row gx-5">
    <div class="col">
     <div class="p-3"><a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover lead" href="inventarioCategorias">categorias</a></div>
    </div>
    <div class="col">
     <div class="p-3"><a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover lead" href="inventario">productos</a></div>
    </div>
</div>
<table  class="table table-dark table-striped tableee"  >
    <thead>
        <tr>
            <th>producto</th>
            <th>precio</th>
            <th>Descripcion</th>
            <th>Stock</th>
            <th>imagen</th>
            <th>Categoria</th>
            <th>acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($products as $product) :?>
        <tr>
            <td><?=$product->Producto ?></td>
            <td><span>$</span><?=$product->Precio ?></td>
            <td><?=$product->Descripcion ?></td>
            <td><?php if($product->Stock) echo 'En Stock' ?></td>
            <td><img class="imgtabla" src="<?=$product->Imagen?>" alt=""></td>
            <td><?=$product->Categoria ?></td>
            <td><a href="eliminar/<?= $product->id_producto?>" class="btn btn-danger">eliminar</a><a class="btn btn-outline-warning" href="editarFormProducto/<?=$product->id_producto?>">editar</a></td>
        </tr>
        <?php endforeach?>
    </tbody>
</table>


<?php include_once 'footer.phtml';



?>