<?php require 'templates/header.phtml'; ?>

<div class="mt-5 w-80 ">
    <form method="POST" action="validar">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text"  class="form-control" id="email" name="user" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password"  class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

