<?php require 'templates/header.phtml'?>
<div class="container overflow-hidden text-center">
  <div class="row gx-5">
    <?php foreach($categories as $categoria) :?>
    <div class="col">
     <div class="p-3"><div class="p-3"><a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover lead" href="Categoria/<?=$categoria->id_categorias?>"><?=$categoria->Categoria?></a></div></div>
    </div>
    <?php endforeach?>
  </div>
</div>
<div class="row grid gap-3 w-80 ml-6">
        <?php foreach($productByCategory as $product):?>
            <div class=" ml-6 card border border-black mb-3 mt-3   " style="width: 18rem;">
                <img class="card-img-top" src="<?=$product->Imagen?>" alt="">
              <div class="card-body">
                <h5 class="card-title"><?= $product->Producto ?></h5>
                <p class="card-text"><?= $product->Categoria ?></p>
                <p class="card-text"><?= $product->Descripcion ?></p>
                <p class="card-text"><?= $product->Marcas ?></p>

                <a href="verMas/<?= $product->id_producto?>" class="btn btn-primary">Ver Más</a>
              </div>
            </div>
        <?php endforeach?>
    </div>

    <?php require 'templates/footer.phtml'?>